export const fieldLabels = {
  lo_id: 'Loan Officer ID',
  loan_type: 'Loan Type',
  purpose_of_loan: '',
  property_type: '',
  applied_amount: 'Required loan amount',

  property_identification_is: '',
  property_value_estimate: '',
  owner_name: '',
  plot_house_flat: '',
  project_society_colony: '',
  pincode: '',
  city: '',
  state: '',
  geo_lat: '',
  geo_long: '',

  applicant_type: 'Primary Applicant',
  first_name: 'First Name',
  middle_name: 'Middle Name',
  last_name: 'Last Name',
  date_of_birth: 'Date of Birth',
  mobile_number: 'Mobile Number',

  id_type: 'ID type',
  id_number: 'ID number',
  selected_address_proof: 'Address proof',
  address_proof_number: 'Address proof number',
  first_name: 'First Name',
  middle_name: 'Middle Name',
  last_name: 'Last Name',
  gender: 'Gender',
  date_of_birth: 'Date of Birth',
  mobile_number: 'Mobile Number',
  father_husband_name: `Father/Husband's name`,
  mother_name: `Mother's name`,
  marital_status: 'Marital Status',
  religion: 'Religion',
  preferred_language: 'Preferred language',
  qualification: 'Qualification',
  email: 'Email',

  current_type_of_residence: 'Type of Residence',
  current_flat_no_building_name: 'Current Flat no/Building name',
  current_street_area_locality: 'Current Street/Area/Locality',
  current_town: 'Current Town',
  current_landmark: 'Current Landmark',
  current_pincode: 'Current Pincode',
  current_city: 'Current City',
  current_state: 'Current State',
  current_no_of_year_residing: 'Current No. of Year Residing',
  permanent_type_of_residence: 'Permanent Type of Residence',
  permanent_flat_no_building_name: 'Permanent Flat no/Building name',
  permanent_street_area_locality: 'Permanent Street/Area/Locality',
  permanent_town: 'Permanent Town',
  permanent_landmark: 'Permanent Landmark',
  permanent_pincode: 'Permanent Pincode',
  permanent_city: 'Permanent City',
  permanent_state: 'Permanent State',
  permanent_no_of_year_residing: 'Current No. of Year Residing',
  permanent_address_same_as_current: ' Permanent address is same as Current address',

  profession: 'Profession',
  company_name: 'Company Name',
  total_income: 'Total Income',
  pf_uan: 'PF UAN',
  no_current_loan: 'No. of Current Loan',
  ongoing_emi: 'Ongoing EMI',
  working_since: 'Working Since',
  mode_of_salary: 'Mode Of Salary',
  flat_no_building_name: 'Flat No Building Name',
  street_area_locality: 'Street Area Locality',
  town: 'Town',
  landmark: 'Landmark',
  pincode: 'Pincode',
  city: 'City',
  state: 'State',
  total_family_number: 'Total Family',
  total_household_income: 'Total Household Income',
  no_of_dependents: 'No. of Dependents',
  business_name: 'Business Name',
  industries: 'Industries',
  gst_number: 'GST Number',
  pention_amount: 'Pention Amount',
  geo_lat: '',
  geo_long: '',
  extra_company_name: 'Extra Company Name',
  extra_industries: 'Extra Industries',
  progress: 0,
};

export const pages = {
  applicant_details: {
    title: 'Applicant Details',
    url: '/lead/applicant-details',
    name: 'applicant_details',
  },
  personal_details: {
    title: 'Personal Details',
    url: '/lead/personal-details',
    name: 'personal_details',
  },
  address_detail: {
    title: 'Address Details',
    url: '/lead/address-details',
    name: 'address_detail',
  },
  work_income_detail: {
    title: 'Work/Income Details',
    url: '/lead/work-income-details',
    name: 'work_income_detail',
  },
  property_details: {
    title: 'Property Details',
    url: '/lead/property-details',
    name: 'propertySchema',
  },
  banking_details: {
    title: 'Banking Details',
    url: '/lead/banking-details',
    name: 'banking_details',
  },
  reference_details: {
    title: 'Reference Details',
    url: '/lead/reference-details',
    name: 'referenceSchema',
  },
  upload_documents: {
    title: 'Upload Documents',
    url: '/lead/upload-documents',
    name: 'upload_documents',
  },
};
