import {
  ApplicantDetailsIcon,
  WorkIncomeIcon,
  UploadIcon,
  ReferenceDetailsIcon,
  QualifierIcon,
  PropertyDetailsIcon,
  PreviewIcon,
  PersonalDetailsIcon,
  LnTIcon,
  BankingDetailsIcon,
  AddressDetailsIcon,
} from '../assets/icons';

export const applicantSteps = [
  {
    title: 'Applicant Details',
    description: 'Name, Mobile Number, Loan Type',
    progress: 0,
    url: '/lead/applicant-details',
    Icon: ApplicantDetailsIcon,
    name: 'applicant_details',
  },
  {
    title: 'Personal Details',
    description: 'OCR, e-KYC, Address',
    progress: 0,
    url: '/lead/personal-details',
    lock: true,
    Icon: PersonalDetailsIcon,
    name: 'personal_details',
  },
  {
    title: 'Address Details',
    description: 'OCR, e-KYC, Address',
    progress: 0,
    url: '/lead/address-details',
    lock: true,
    Icon: AddressDetailsIcon,
    name: 'address_detail',
  },
  {
    title: 'Work/Income Details',
    description: 'Profession details, Family Income',
    progress: 0,
    url: '/lead/work-income-details',
    lock: true,
    Icon: WorkIncomeIcon,
    name: 'work_income_detail',
  },
  {
    title: 'Qualifier is not activated',
    description: 'Complete Applicant, Personal, Address and Work & Income details to activate',
    url: '/lead/work-income-details',
    hideProgress: true,
    Icon: QualifierIcon,
    name: 'qualifier',
  },
  {
    title: 'L&T Charges',
    description: 'Fee details',
    progress: 0,
    url: '/lead/lnt-charges',
    lock: true,
    Icon: LnTIcon,
    name: 'lt_charges',
  },
  {
    title: 'Property Details',
    description: 'Profession details, Family Income',
    progress: 0,
    url: '/lead/property-details',
    lock: true,
    Icon: PropertyDetailsIcon,
    name: 'property_details',
  },
  {
    title: 'Banking Details',
    description: 'IFSC Details, Bank Statement',
    progress: 0,
    url: '/lead/banking-details',
    lock: true,
    Icon: BankingDetailsIcon,
  },
  {
    title: 'Reference Details',
    description: 'Reference person name, Mobile number',
    progress: 0,
    url: '/lead/reference-details',
    lock: true,
    Icon: ReferenceDetailsIcon,
    name: 'reference_details',
  },
  {
    title: 'Upload Documents',
    description: 'Aadhar, PAN, Property document',
    progress: 0,
    url: '/lead/upload-documents',
    lock: true,
    Icon: UploadIcon,
  },
  {
    title: 'Preview',
    description: '',
    url: '/lead/upload-documents',
    hideProgress: true,
    Icon: PreviewIcon,
  },
];

export const coApplicantSteps = [
  {
    title: 'Applicant Details',
    description: 'Name, Mobile Number, Loan Type',
    progress: 0,
    url: '/lead/applicant-details',
    Icon: ApplicantDetailsIcon,
    name: 'applicant_details',
  },
  {
    title: 'Personal Details',
    description: 'OCR, e-KYC, Address',
    progress: 0,
    url: '/lead/personal-details',
    lock: true,
    Icon: PersonalDetailsIcon,
    name: 'personal_details',
  },
  {
    title: 'Address Details',
    description: 'OCR, e-KYC, Address',
    progress: 0,
    url: '/lead/address-details',
    lock: true,
    Icon: AddressDetailsIcon,
    name: 'address_detail',
  },
  {
    title: 'Work/Income Details',
    description: 'Profession details, Family Income',
    progress: 0,
    url: '/lead/work-income-details',
    lock: true,
    Icon: WorkIncomeIcon,
    name: 'work_income_detail',
  },
  {
    title: 'Qualifier is not activated',
    description: 'Complete Applicant, Personal, Address and Work & Income details to activate',
    url: '/lead/work-income-details',
    hideProgress: true,
    Icon: QualifierIcon,
  },
  {
    title: 'Banking Details',
    description: 'IFSC Details, Bank Statement',
    progress: 0,
    url: '/lead/banking-details',
    lock: true,
    Icon: BankingDetailsIcon,
  },
  {
    title: 'Upload Documents',
    description: 'Aadhar, PAN, Property document',
    progress: 0,
    url: '/lead/upload-documents',
    lock: true,
    Icon: UploadIcon,
  },
];
